name: Build and pack (v2)

on:
  workflow_dispatch:
  push:
    branches:
      - stable
      - dev

  pull_request:
    branches:
      - stable
      - dev

permissions:
  contents: read

env:
  # Initialize vars context by reading it from env context
  _: ${{ vars._ }}

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macOS-latest ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        if: ${{ runner.os != 'macOS' }}
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install --with pyinstaller

      - name: Install dependencies (macOS)
        if: ${{ runner.os == 'macOS' }}
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="/Users/runner/.local/bin:$PATH"
          poetry install --with pyinstaller

      - name: Build (Windows)
        if: ${{ runner.os == 'Windows' }}
        run: |
          poetry run pyinstaller ${{ vars.V2_PATH }}__main__.py --name main.exe --onefile --add-data ${{ vars.V2_PATH }}geetest-webui/*:geetest-webui
          move dist\main.exe .\

      - name: Build
        if: ${{ runner.os != 'Windows' }}
        run: |
          poetry run pyinstaller ${{ vars.V2_PATH }}__main__.py --name main --onefile --add-data ${{ vars.V2_PATH }}geetest-webui/*:geetest-webui
          mv ./dist/main ./

      - name: Clean up
        run: |
          poetry run pyinstaller --clean ${{ vars.V2_PATH }}__main__.py

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: Mys_Goods_Tool_v2-${{ runner.os }}-x86_64
          path: |
            main*
