name: Build and pack

on:
  push:
    branches:
    - stable
    - dev
    branches-ignore:    
      - 'stable/**-README.md'
      - 'stable/**-LICENSE'
      - 'dev/**-README.md'
      - 'dev/**-LICENSE'
  pull_request:
    branches:
    - stable
    - dev
    branches-ignore:    
      - 'stable/**-README.md'
      - 'stable/**-LICENSE'
      - 'dev/**-README.md'
      - 'dev/**-LICENSE'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macOS-latest ]
        
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
        
    - name: Build main(Windows)
      if: ${{ runner.os == 'Windows' }}
      run: |
        pyinstaller -F ./main.py
        move dist\main.exe .\
    
    - name: Build main
      if: ${{ runner.os != 'Windows' }}
      run: |
        pyinstaller -F ./main.py
        mv ./dist/main ./
        
    - name: Cleaning up build(Windows)
      if: ${{ runner.os == 'Windows' }}
      run: |
        del dist
        del *.spec
        del main.py
        move build build_main
        
    - name: Cleaning up main build
      if: ${{ runner.os != 'Windows' }}
      run: |
        rm -rf dist/ __pycache__/ build/ *.spec main.py
        
    - name: Build tool(Windows)
      if: ${{ runner.os == 'Windows' }}
      run: |
        pyinstaller -F ./tool.py
        move dist\tool.exe .\
    
    - name: Build tool
      if: ${{ runner.os != 'Windows' }}
      run: |
        pyinstaller -F ./tool.py
        mv ./dist/tool ./
        
    - name: Cleaning up tool build(Windows)
      if: ${{ runner.os == 'Windows' }}
      run: |
        del dist
        del *.spec
        del tool.py
        
    - name: Cleaning up build
      if: ${{ runner.os != 'Windows' }}
      run: |
        rm -rf dist/ __pycache__/ build/ *.spec tool.py
        
    - name: Upload build
      uses: actions/upload-artifact@v3
      with:
        name: Mys_Goods_Tool-${{ runner.os }}-x86_64
        path: |
          ./main*
          ./tool*
          ./config.ini
          ./logs
