name: Build and pack

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macOS-latest ]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
    - name: Build the applications
      run: |
        pyinstaller -F ./main.py
        pyinstaller -F ./tool.py
    - name: Upload build
      uses: actions/upload-artifact@v3
      with:
        name: Mys_Goods_Tool-${{ runner.os }}-x86_64
        path: |
          ./dist/main*
          ./dist/tool*
          ./config.ini
          ./logs
