name: Build and pack (v2)

on:
  workflow_dispatch:
  push:
    branches:
      - stable
      - dev

  pull_request:
    branches:
      - stable
      - dev

permissions:
  contents: read

env:
  # Initialize vars context by reading it from env context
  _: ${{ vars._ }}
  windows-poetry-path: C:\Users\runneradmin\AppData\Roaming\Python\Scripts\poetry

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macOS-latest ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies (Linux)
        if: ${{ runner.os == 'Linux' }}
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install --with pyinstaller

      - name: Install dependencies (macOS)
        if: ${{ runner.os == 'macOS' }}
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="/Users/runner/.local/bin:$PATH"
          poetry install --with pyinstaller

      - name: Install dependencies (Windows)
        if: ${{ runner.os == 'Windows' }}
        run: |
          (Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | py -
          ${{ env.windows-poetry-path }} install --with pyinstaller

      - name: Build (Linux)
        if: ${{ runner.os == 'Linux' }}
        run: |
          poetry run pyinstaller ${{ vars.V2_PATH }}__main__.py --name main --onefile --add-data ${{ vars.V2_PATH }}geetest-webui/*:geetest-webui
          mv ./dist/main ./

      - name: Build (macOS)
        if: ${{ runner.os == 'macOS' }}
        run: |
          export PATH="/Users/runner/.local/bin:$PATH"
          poetry run pyinstaller ${{ vars.V2_PATH }}* --name main --onefile --add-data ${{ vars.V2_PATH }}geetest-webui/*:geetest-webui
          mv ./dist/main ./

      - name: Build (Windows)
        if: ${{ runner.os == 'Windows' }}
        run: |
          ${{ env.windows-poetry-path }} run pyinstaller .\mys_goods_tool\__main__.py --name main.exe --onefile --add-data .\mys_goods_tool\geetest-webui\*:geetest-webui
          move dist\main.exe .\

      - name: Clean up (Linux)
        if: ${{ runner.os == 'Linux' }}
        run: |
          poetry run pyinstaller --clean ${{ vars.V2_PATH }}__main__.py
          rm *.spec

      - name: Clean up (macOS)
        if: ${{ runner.os == 'macOS' }}
        run: |
          export PATH="/Users/runner/.local/bin:$PATH"
          poetry run pyinstaller --clean ${{ vars.V2_PATH }}__main__.py
          rm *.spec

      - name: Clean up (Windows)
        if: ${{ runner.os == 'Windows' }}
        run: |
          ${{ env.windows-poetry-path }} run pyinstaller --clean ${{ vars.V2_PATH }}__main__.py
          del *.spec

      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: Mys_Goods_Tool_v2-${{ runner.os }}-x86_64
          path: |
            main*
